name: 'Install OpenSearch with Plugin'
description: 'Installs and run OpenSearch docker'

inputs:
  opensearch_version:
    description: 'The version of OpenSearch core'
    required: true

  security_plugin_version:
    description: 'The version of security plugin'
    required: true

  plugin-name:
    description: 'The the name of the plugin to use, such as opensearch-security'
    required: true
  
  plugin-zip:
    description: 'The name of the zip file for the plugin hosted on docker-host i.e. security-plugin.zip'
    required: true

  plugin-start-script:
    description: 'The file name for the configuration script for the plugin such as install_demo_configurations -- may not be needed for every plugin'
    required: false

runs:
  using: "composite"
  steps:
      - name: Download OpenSearch Core
        run: |
          wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/${{ inputs.opensearch_version }}/latest/linux/x64/tar/builds/opensearch/dist/opensearch-min-${{ inputs.opensearch_version }}-linux-x64.tar.gz
          tar -xzf opensearch-*.tar.gz
          rm -f opensearch-*.tar.gz
        shell: bash
          
      - name: Download OpenSearch Security Plugin
        run: wget -O ${{ inputs.plugin-name }}.zip https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/${{ inputs.opensearch_version }}/latest/linux/x64/tar/builds/opensearch/plugins/${{ inputs.plugin-name }}-${{ inputs.security_plugin_version }}.zip
        shell: bash

      - name: Run OpenSearch with plugin
        run: |
          cat > os-ep.sh <<EOF
          yes | opensearch-plugin install file:///docker-host/${{ inputs.plugin-zip }}
          chmod +x plugins/${{ inputs.plugin-name }}/tools/${{ inputs.plugin-start-script }}.sh
          yes | plugins/${{ inputs.plugin-name }}/tools/${{ inputs.plugin-start-script }}.sh
          echo "plugins.security.unsupported.restapi.allow_securityconfig_modification: true" >> /opensearch/config/opensearch.yml
          chown 1001:1001 -R /opensearch
          su -c "/opensearch/bin/opensearch" -s /bin/bash opensearch
          EOF
          docker build -t opensearch-test:latest -f- . <<EOF
          FROM ubuntu:latest
          COPY --chown=1001:1001 os-ep.sh /docker-host/
          COPY --chown=1001:1001 ${{ inputs.plugin-name }}.zip /docker-host/${{ inputs.plugin-zip }}
          COPY --chown=1001:1001 opensearch* /opensearch/
          RUN chmod +x /docker-host/os-ep.sh
          RUN useradd -u 1001 -s /sbin/nologin opensearch
          ENV PATH="/opensearch/bin:${PATH}"
          WORKDIR /opensearch/
          ENTRYPOINT /docker-host/os-ep.sh
          EOF
          docker run -d -p 9200:9200 -p 9600:9600 -i opensearch-test:latest
        shell: bash
