name: Reusable Setup

on: 
  workflow_call:

env:
  TEST_BROWSER_HEADLESS: 1
  CI: 1
  FTR_PATH: 'ftr'
  START_CMD: 'node ../scripts/opensearch_dashboards --dev --no-base-path --no-watch --opensearch_security.multitenancy.enable_aggregation_view=true'
  OPENSEARCH_SNAPSHOT_CMD: 'node ../scripts/opensearch snapshot'
  SPEC: 'cypress/integration/plugins/security-dashboards-plugin/aggregation_view.js,'
  
jobs:
  tests:
    name: Set up OpenSearch and Dashboards
    runs-on: ubuntu-latest
    steps:
      - name: Download OpenSearch Core
        run: |
          wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/dist/opensearch-min-3.0.0-linux-x64.tar.gz
          tar -xzf opensearch-*.tar.gz
          rm -f opensearch-*.tar.gz
          
      - name: Download OpenSearch Security Plugin
        run: wget -O opensearch-security.zip https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip
        

      - name: Run OpenSearch with plugin
        run: |
          cat > os-ep.sh <<EOF
          yes | opensearch-plugin install file:///docker-host/security-plugin.zip
          chmod +x plugins/opensearch-security/tools/install_demo_configuration.sh
          yes | plugins/opensearch-security/tools/install_demo_configuration.sh
          echo "plugins.security.unsupported.restapi.allow_securityconfig_modification: true" >> /opensearch/config/opensearch.yml
          chown 1001:1001 -R /opensearch
          su -c "/opensearch/bin/opensearch" -s /bin/bash opensearch
          EOF
          docker build -t opensearch-test:latest -f- . <<EOF
          FROM ubuntu:latest
          COPY --chown=1001:1001 os-ep.sh /docker-host/
          COPY --chown=1001:1001 opensearch-security.zip /docker-host/security-plugin.zip
          COPY --chown=1001:1001 opensearch* /opensearch/
          RUN chmod +x /docker-host/os-ep.sh
          RUN useradd -u 1001 -s /sbin/nologin opensearch
          ENV PATH="/opensearch/bin:${PATH}"
          WORKDIR /opensearch/
          ENTRYPOINT /docker-host/os-ep.sh
          EOF
          docker run -d -p 9200:9200 -p 9600:9600 -i opensearch-test:latest
            
      - name: Check OpenSearch Running
        continue-on-error: true
        run: curl -XGET https://localhost:9200 -u 'admin:admin' -k
